### PR TITLE
issue-38 Remove hard coding of urls

### PR DESCRIPTION
**Pull request by martsberger**
For issue 38, we're replacing all hard coded urls with reverse lookups.

Currently, nothing works because the master branch gives me this error when running ./manage.py:
```
ImportError: No module named alliance.config.settings.base
```

I think we should keep a goal that it is always possible to checkout master and run the local server. I know we can't keep out every bug, but we should be able to try "./manage.py runserver" and see that it works before we merge to master.

### CODE REVIEW

**Comment by kdflint** [comment]
Offending line 6 in manage.py
`os.environ.setdefault("DJANGO_SETTINGS_MODULE", "alliance.config.settings.base")`

If a system env variable named DJANGO_SETTINGS_MODULE is not set, then the importer is using a default value of `alliance.config.settings.base`. This value must not be correct for local runtimes.

What is the value that will work in a local install? We should discover that and update the default value in line 6 accordingly.

In our dev/prod environment at heroku, this env variable is set to `alliance.config.settings.dev`, which works. (No import errors being thrown there. Running code is triple confirmed as pushed from alliance-community HEAD:master)

screenshot from 2015-11-08 13 17 22

I don't know why, but path resolutions have been slightly different at heroku than for local in a couple instances.

**Comment by kdflint** [comment]
Inspiration on the treadmill this afternoon... the difference between our local deployments and a heroku deployment is that on heroku we run our app on gunicorn using WSGI. Locally we  use the django development server. It makes sense that this path would resolve differently under these different runtime conditions.

On heroku we get to our django settings through wsgi.py and locally through manage.py

I bet local deploys would be happy with `config.settings.dev` in line 6 of manage.py. Can someone give this a try? (I don't have a local install.)

**Comment by martsberger** [comment]
Close, line 6 of manage.py is using alliance.config.settings.base instead
of config.settings.base.

**Comment by hectron** [comment]
That makes sense.

@kdflint , at stand up yesterday, I mentioned that we should simplify the settings. I will submit a pull request with the proposed changes.

**Comment by hectron** [comment]
@martsberger , I will pull down this branch and test it out to see if it is valid. Once everything is ready, this can get merged in and accepted. Thanks!

**Comment by hectron** [comment]
Great job, @martsberger !

**Pull request merged**
